 <!-- jQuery -->
        <script src="<?=  base_url()?>assets/js/jquery.min.js"></script>
        <script src="<?=  base_url()?>assets/js/modernizr-2.6.2.min.js"></script>
        <script src="<?=  base_url()?>assets/js/jquery.easing.1.3.js"></script>
        <script src="<?=  base_url()?>assets/js/bootstrap.min.js"></script>
        <script src="<?=  base_url()?>assets/js/jquery.waypoints.min.js"></script>
        <script src="<?=  base_url()?>assets/js/jquery.flexslider-min.js"></script>
        <script src="<?=  base_url()?>assets/js/sticky-kit.min.js"></script>
        <script src="<?=  base_url()?>assets/js/jquery.fancybox.min.js"></script>
        <script src="<?=  base_url()?>assets/js/main.js"></script>